### ISSUE TITLE
Attempted to beginRule error message

### ISSUE THREAD

**Issue by leuschel** [eventB-Soton/XEventB#34]
I had old Camille open on the generated file; I saved a change in CamilleX and then reloaded the contents in Camille and got the following error message, which I guess is coming from new CamilleX?

![screenshot 2018-11-13 at 18 40 08](https://user-images.githubusercontent.com/1742246/48432071-a88f0280-e773-11e8-8a56-70ebc7553f21.png)

**Comment by leuschel** [comment]
Here is the part from the error log:

!ENTRY org.eclipse.ui.workbench 4 2 2018-11-13 18:39:36.321
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.IllegalArgumentException: Attempted to beginRule: R/, does not match outer scope rule: P/CamilleXTests
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:134)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:349)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:63)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:308)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:121)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2188)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2235)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.emf.common.ui.MarkerHelper.deleteMarkers(MarkerHelper.java:240)
	at org.eclipse.emf.common.ui.MarkerHelper.deleteMarkers(MarkerHelper.java:231)
	at org.eclipse.emf.edit.ui.util.EditUIMarkerHelper.deleteMarkers(EditUIMarkerHelper.java:203)
	at org.eventb.texteditor.ui.build.ast.AstBuilder.createAST(AstBuilder.java:116)
	at org.eventb.texteditor.ui.build.ast.AstBuilder.build(AstBuilder.java:71)
	at org.eventb.texteditor.ui.build.ast.AstBuilder.run(AstBuilder.java:51)
	at org.eventb.texteditor.ui.build.Builder.run(Builder.java:42)
	at org.eventb.texteditor.ui.editor.DocumentProvider.reconcileContent(DocumentProvider.java:216)
	at org.eventb.texteditor.ui.editor.DocumentProvider.setDocumentContent(DocumentProvider.java:147)
	at org.eclipse.ui.editors.text.FileDocumentProvider.handleElementContentChanged(FileDocumentProvider.java:809)
	at org.eclipse.ui.editors.text.FileDocumentProvider.doSynchronize(FileDocumentProvider.java:526)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider$1SynchronizeOperation.execute(AbstractDocumentProvider.java:951)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider$DocumentProviderOperation.run(AbstractDocumentProvider.java:72)
	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:68)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:73)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:63)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider.executeOperation(AbstractDocumentProvider.java:536)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider.synchronize(AbstractDocumentProvider.java:960)
	at org.eclipse.ui.texteditor.AbstractTextEditor.handleEditorInputChanged(AbstractTextEditor.java:4730)
	at org.eclipse.ui.texteditor.StatusTextEditor.handleEditorInputChanged(StatusTextEditor.java:285)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.handleEditorInputChanged(AbstractDecoratedTextEditor.java:1485)
	at org.eventb.texteditor.ui.editor.EventBTextEditor.handleActive(EventBTextEditor.java:366)
	at org.eventb.texteditor.ui.editor.EventBTextEditor.access$0(EventBTextEditor.java:363)
	at org.eventb.texteditor.ui.editor.EventBTextEditor$ActivateListener.partActivated(EventBTextEditor.java:381)
	at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4990)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4987)
	at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4975)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:212)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:756)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:681)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:95)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.lambda$0(ContributedPartRenderer.java:60)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1621)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1584)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:3434)
	at org.eclipse.swt.widgets.Canvas.sendFocusEvent(Canvas.java:76)
	at org.eclipse.swt.widgets.Display.checkFocus(Display.java:672)
	at org.eclipse.swt.widgets.Shell.makeFirstResponder(Shell.java:1303)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5909)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(Native Method)
	at org.eclipse.swt.internal.cocoa.NSWindow.makeFirstResponder(NSWindow.java:198)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1477)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1457)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:3868)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1089)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setFocus(AbstractTextEditor.java:6191)
	at org.eclipse.ui.texteditor.StatusTextEditor.setFocus(StatusTextEditor.java:144)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.delegateSetFocus(CompatibilityPart.java:216)
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:311)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:107)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.focusGui(PartRenderingEngine.java:789)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.setFocus(ContributedPartRenderer.java:103)
	at org.eclipse.swt.custom.CTabItem.setFocus(CTabItem.java:332)
	at org.eclipse.swt.custom.CTabFolder.setFocus(CTabFolder.java:2631)
	at org.eclipse.swt.widgets.Control.fixFocus(Control.java:1382)
	at org.eclipse.swt.widgets.Control.setVisible(Control.java:4411)
	at org.eclipse.swt.widgets.ToolBar.setVisible(ToolBar.java:769)
	at org.eclipse.swt.custom.CTabFolder.setItemSize(CTabFolder.java:2801)
	at org.eclipse.swt.custom.CTabFolder.updateItems(CTabFolder.java:3784)
	at org.eclipse.swt.custom.CTabFolder.updateItems(CTabFolder.java:3717)
	at org.eclipse.swt.custom.CTabFolder.onResize(CTabFolder.java:2110)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:335)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1506)
	at org.eclipse.swt.widgets.Control.resized(Control.java:3395)
	at org.eclipse.swt.widgets.Composite.resized(Composite.java:985)
	at org.eclipse.swt.widgets.Control.setFrameSize(Control.java:3961)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5791)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSView.setFrameSize(NSView.java:296)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3693)
	at org.eclipse.swt.widgets.Control.setSize(Control.java:4253)
	at org.eclipse.swt.widgets.Control.pack(Control.java:2774)
	at org.eclipse.swt.widgets.Control.pack(Control.java:2748)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.adjustTopRight(StackRenderer.java:820)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1309)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.lambda$0(LazyStackRenderer.java:68)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4871)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:173)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer$3.widgetSelected(StackRenderer.java:1053)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3187)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1870)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:328)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by cfsnook** [comment]
I am guessing a bit but looks like you have nested Jobs running with the outer one scoped on a specific project called CamilleXTests and the inner one scoped on an unspecified resource.

**Comment by tshoang** [comment]
This seems to be related to the Rodin Editor (org.eventb.texteditor.ui.editor.EventBTextEditor). We haven't seen similar errors like this for quite a while, so I close this issue for now.
